version: "3.8"

services:

  eureka-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - backend

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - backend

  shopping-store:
    build: ./commerce/shopping-store
    depends_on:
      - config-server
      - eureka-server
    networks:
      - backend

  shopping-cart:
    build: ./commerce/shopping-cart
    depends_on:
      - config-server
      - eureka-server
    networks:
      - backend

  warehouse:
    build: ./commerce/warehouse
    depends_on:
      - config-server
      - eureka-server
    networks:
      - backend

  smart-home-tech-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sht
      POSTGRES_USER: sh
      POSTGRES_PASSWORD: sh
    networks:
      - backend

networks:
  backend:
