spring:
  application:
    name: shopping-store

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://smart-home-tech-db:5432/sht?currentSchema=store
    username: sh
    password: sh

  jpa:
    hibernate.ddl-auto: none
    show-sql: true

server.port: 0
