@namespace("ru.yandex.practicum.kafka.telemetry.event")
protocol SensorsSnapshotProtocol {

	import idl "SensorEvent.avdl";

	record SensorsSnapshotAvro {
		string hubId;                      // Идентификатор хаба
		timestamp_ms timestamp;            // Временная отметка снимка
		map<SensorStateAvro> sensorsState; // Коллекция состояний датчиков, сопоставленных с идентификаторами устройств
	}

	record SensorStateAvro {
		timestamp_ms timestamp;  // Время отправки показаний
		union {                  // Показания конкретного датчика
			ClimateSensorAvro,
			LightSensorAvro,
			MotionSensorAvro,
			SwitchSensorAvro,
			TemperatureSensorAvro
		} data;
	}
}
